interval: 10
path: ./test
repos:
   - url: "git@github.com:halvardssm/js-helpers.git"
owners:
   - provider: "github_user"
     namespace: "leifssm"
   - provider: "github_org"
     namespace: "simplyundoable"
   - provider: "gitlab_org"
     namespace: "tester174"
   - provider: "gitlab_user"
     namespace: "halvardm"

